tap "buo/cask-upgrade"
tap "dart-lang/dart"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "jounqin/x"
tap "miderwong/flutter"
tap "thoughtbot/formulae"
brew "node"
brew "angular-cli"
brew "asciinema"
brew "caddy"
brew "cocoapods"
brew "fd"
brew "fzy"
brew "git"
brew "git-extras"
brew "git-flow"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "hub"
brew "hubflow"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "ios-deploy"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "nginx"
brew "nnn"
brew "now-cli"
brew "nvm"
brew "p7zip"
brew "pandoc"
brew "ruby"
brew "shellcheck"
brew "thefuck"
brew "travis"
brew "typescript"
brew "yarn"
brew "zsh"
brew "dart-lang/dart/dart"
brew "jesseduffield/lazydocker/lazydocker"
brew "miderwong/flutter/flutter"
brew "thoughtbot/formulae/rcm"
cask "alfred"
cask "android-studio"
cask "axure-rp"
cask "baidunetdisk"
cask "bartender"
cask "dash"
cask "dingtalk"
cask "docker"
cask "font-fira-code"
cask "google-chrome"
cask "iterm2"
cask "itsycal"
cask "java"
cask "keka"
cask "kekadefaultapp"
cask "lunar"
cask "motrix"
cask "one-switch"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "shadowsocksx-ng-r"
cask "sip"
cask "sketch"
cask "slack"
cask "suspicious-package"
cask "switchhosts"
cask "tencent-lemon"
cask "touch-bar-simulator"
cask "typora"
cask "upic"
cask "visual-studio-code"
cask "webpquicklook"
cask "zeplin"
cask "jounqin/x/aerial-beta"
cask "jounqin/x/unlox-beta"
mas "Image2icon", id: 992115977
mas "Paste", id: 967805235
mas "QQ", id: 451108668
mas "QQ影音", id: 1467163328
mas "QQ音乐", id: 595615424
mas "SPlayer", id: 414675434
mas "Xcode", id: 497799835
mas "企业微信", id: 1189898970
mas "印象笔记", id: 1356055347
mas "微信", id: 836500024
mas "截图", id: 1059334054
mas "看图", id: 1314842898
