tap "buo/cask-upgrade"
tap "dart-lang/dart"
tap "github/gh"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "jounqin/x"
tap "mathildetech/alauda", "git@bitbucket.org:mathildetech/homebrew-alauda.git"
tap "miderwong/flutter"
tap "thoughtbot/formulae"
brew "node"
brew "angular-cli"
brew "asciinema"
brew "caddy"
brew "cocoapods"
brew "fd"
brew "ffmpeg"
brew "fzy"
brew "git"
brew "git-extras"
brew "git-flow"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "hub"
brew "hubflow"
brew "libusbmuxd"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "ios-deploy"
brew "jq"
brew "kubernetes-cli"
brew "lazydocker"
brew "mas"
brew "mysql"
brew "nginx"
brew "nnn"
brew "now-cli"
brew "nvm"
brew "p7zip"
brew "pandoc"
brew "pnpm"
brew "ruby"
brew "shellcheck"
brew "thefuck"
brew "typescript"
brew "yarn"
brew "zsh"
brew "dart-lang/dart/dart"
brew "github/gh/gh"
brew "mathildetech/alauda/console-cli"
brew "miderwong/flutter/flutter"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "aerial"
cask "alfred"
cask "aliwangwang"
cask "android-studio"
cask "axure-rp"
cask "baidunetdisk"
cask "bartender"
cask "dash"
cask "dingtalk"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "itsycal"
cask "java"
cask "keka"
cask "kekadefaultapp"
cask "lunar"
cask "microsoft-teams"
cask "motrix"
cask "mysqlworkbench"
cask "one-switch"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "shadowsocksx-ng-r"
cask "sip"
cask "sketch"
cask "sogouinput"
cask "station"
cask "suspicious-package"
cask "switchhosts"
cask "tencent-lemon"
cask "typora"
cask "unlox"
cask "upic"
cask "visual-studio-code"
cask "webpquicklook"
cask "zeplin"
mas "Image2icon", id: 992115977
mas "iMovie 剪辑", id: 408981434
mas "Moon FM", id: 1465712037
mas "Paste", id: 967805235
mas "QQ", id: 451108668
mas "QQ影音", id: 1467163328
mas "QQ音乐", id: 595615424
mas "SPlayer", id: 414675434
mas "Xcode", id: 497799835
mas "企业微信", id: 1189898970
mas "微信", id: 836500024
mas "截图", id: 1059334054
mas "看图", id: 1314842898
