name: ci

on:
  - push
  - pull_request

jobs:
  ci:
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup on macOS
        if: matrix.os == 'macOS-latest'
        run: bash ./setup.sh

      - name: Setup on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install build-essential
          bash ./setup.sh
