name: ci

on: [push, pull_request]

jobs:
  default:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Setup on macOS
        if: matrix.os == 'macOS-latest'
        run: sh ./setup.sh
        env:
          CI: true

      - name: Setup on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install build-essential
          yes | sh ./setup.sh
        env:
          CI: true
